### ISSUE TITLE
gulp build doesn't exit

### ISSUE THREAD

**Issue by amoscatelli** [jberet/jsr352#104]
as title says

the problem is related to this piace of code inside bundle task
    
       return b.bundle()
        .on('error', plugins.util.log.bind(plugins.util, 'Browserify Error'))
        .pipe(source('bundle.js'))

        //minify with source map file
        .pipe(buffer())
        //.pipe(plugins.sourcemaps.init({loadMaps: true}))
        .pipe(plugins.if(!isDebug(), plugins.uglify()))
        // Add transformation tasks to the pipeline here.
        //.pipe(plugins.sourcemaps.write('./'))

        .pipe(gulp.dest(distDir));

inside gulpfile.js

please fix this, otherwise automatic building (without manually CTRL+C) would be impossible

thank you

**Comment by chengfang** [comment]
The reason gulp doesn't exit is to watch any future changes in files and if necessary update the build.  However, we do need support the case that users just want to build and exit.

**Comment by amoscatelli** [comment]
gulp build is not serving files, are you sure it's watching for updates ?

**Comment by chengfang** [comment]
gulp build task watches for file changes and will rebuild the bundle when it detects changes.

**Comment by amoscatelli** [comment]
it's fixed now, thank you
