### ISSUE TITLE
According JBeret specification JBeret should be able to @Inject @BatchProperty File file, but it works only in special curcumstance.

### ISSUE THREAD

**Issue by MBHock** [jberet/jsr352#115]
I have a class as follows:

public class FileListPartitionMapper implements PartitionMapper {

  private static final String FILE_NAME = "fileName";

  @Inject
  @BatchProperty(name = "fileNamePattern")
  private String fileNamePattern;

  @Inject
  @BatchProperty(name = "importPath")
  private String importPath;

  /*
   * (non-Javadoc)
   *
   * @see javax.batch.api.partition.PartitionMapper#mapPartitions()
   */
  @Override
  public PartitionPlan mapPartitions() throws Exception {

    List<File> matchedFiles = Files.list(Paths.get(importPath)).map(Path::toFile).filter(File::isFile).filter(file -> file.getName().matches(fileNamePattern))
        .collect(Collectors.toList());

    PartitionPlan partitionPlan = new PartitionPlanImpl();
    partitionPlan.setThreads(10);

    int partitionNumber = matchedFiles.size();
    partitionPlan.setPartitions(partitionNumber);

    Properties[] partitionProperties = new Properties[partitionNumber];
    partitionPlan.setPartitionProperties(partitionProperties);

    for (int indexPartition = 0; indexPartition < partitionNumber; indexPartition++) {
      Properties prop = new Properties();
      // prop.setProperty(FILE_NAME, matchedFiles.get(indexPartition).getPath()); // Set Property as String is commented out here.
      prop.put(FILE_NAME, matchedFiles.get(indexPartition)); // Hier I am putting the file object in the Properteis, as Properties backed by Map<Object, Object> it must be okay.
      partitionProperties[indexPartition] = prop;
    }

    return partitionPlan;
  }
}

My Reader class looks as follows (for simplification I removed most of the code except Injection point).

public class FileReader implements ItemReader {

  private static final String FILE_NAME = "fileName";

  @Inject
  @BatchProperty(name = FILE_NAME)
  private File file; // Here the file Object is null

....
}

Now if I commented out the following line in my FileListPartitionMapper class, as follows:
      prop.setProperty(FILE_NAME, matchedFiles.get(indexPartition).getPath()); // this method except only String key and String value.

and commented in the following line:
     prop.put(FILE_NAME, matchedFiles.get(indexPartition));

then in my FileReader class, the file-object is not null anymore.

Short conclusion of the Problem is as follows: if we use properties.setProperty(String key, String value), then @Inject @BatchProperty works fine, whereas properties.put(Object key, Object value) is preferrable but DOES NOT work.

However, I did more investigation and I found that JBeret uses "org.jberet.job.model.Properties", which uses only String key and String value. Hence it expects java.util.Properties must hold String key and String value.

**Comment by chengfang** [comment]
Batch jobs are defined in xml format and thus all batch job configurations are expressed in string-based values.  I think this is a pretty fundamental part of the batch spec (JSR 352), though I have to admit this does impose some restrictions on batch applications, for instance, there is no typed non-string objects for configuration.

From a technical point of view, java.util.Properties are used in various parts of the spec to hold job parameters, partition properties, etc.  This also implies string-based keys and values are expected.  Since java.util.Properties is a subclass of java.util.Hashtable, so you can still call its put method to add non-string values, but this value may very likely be ignored.

**Comment by chengfang** [comment]
To inject object types into batch artifacts with more flexibility, you may want to consider using CDI.  WE use CDI injections in some of the batch artifacts in jberet-support modules, for instance,

https://github.com/jberet/jberet-support/blob/master/src/main/java/org/jberet/support/io/JmsItemReaderWriterBase.java#L41
