### ISSUE TITLE
Does JBeret support Java11?

### ISSUE THREAD

**Issue by kiyotis** [jberet/jsr352#121]
WildFly supported Java11 in 1.5.
Has JBeret been tested with Java11?
If JBeret does not support Java11, will JBeret have plans to support Java11?

**Comment by hielkehoeve** [comment]
We are using WF16 with Java11 in production and are experiencing no problems at all.

**Comment by chengfang** [comment]
JBeret is integrated into WildFly to provide enterprise batch processing functionality.  And JBeret is tested and supported as part of WildFly and JBoss EAP.  So whatever version of Java is supported by WildFly should also work with JBeret.

**Comment by kiyotis** [comment]
Thank you for your quick reply. very helpful.
