### ISSUE TITLE
user guide

### ISSUE THREAD

**Issue by ccleve** [jberet/jsr352#148]
The link to the JBeret user guide / documentation is dead. It just goes to the gitbook site.

**Comment by chengfang** [comment]
Thanks for the notice. Looks like gitbook website has gone through some re-org. I'll update https://docs.jboss.org/jberet/ to point to the correct location: https://jberet.gitbooks.io/jberet-user-guide/content/

**Comment by chengfang** [comment]
Updated the jboss.org docs site (https://docs.jboss.org/jberet/latest/) to the correct url for JBeret User Guide.
