### ISSUE TITLE
ItemWriter.close() called twice

### ISSUE THREAD

**Issue by Mobe91** [jberet/jsr352#22]
When I run a partitioned step, the ItemWriter's `close()` method is called twice.
I think the problem lies in [ChunkRunner.run()](https://github.com/jberet/jsr352/blob/master/jberet-core/src/main/java/org/jberet/runtime/runner/ChunkRunner.java#L196).
The `itemWriter` reference is not set to null after closing without exception and therefore the [final call to safeClose()](https://github.com/jberet/jsr352/blob/master/jberet-core/src/main/java/org/jberet/runtime/runner/ChunkRunner.java#L232) will call `ItemWriter.close()` again.

The same probably holds for the `ItemReader.close()` though I did not actually test it.

**Comment by chengfang** [comment]
See https://issues.jboss.org/browse/JBERET-165 (ItemReaders and ItemWriters are closed twice)

Fixed in PR https://github.com/jberet/jsr352/pull/57 

The fix will be included in JBeret 1.2.0.Beta1, WildFly 10 Beta1 (maybe).
