### ISSUE TITLE
Support Java 17

### ISSUE THREAD

**Issue by radcortez** [jberet/jsr352#246]
One of the main issues right now is with the `WildflySecurityManager`.

Maybe we should remove it altogether?

**Comment by chengfang** [comment]
Not sure if removing WildflySecurityManager will fully fix it.  In WildFly, we use the workaround with jdk 17:
```xml
        <modular.jdk.args>
            --add-exports=java.desktop/sun.awt=ALL-UNNAMED
            --add-opens=java.base/java.io=ALL-UNNAMED
            --add-opens=java.base/java.lang=ALL-UNNAMED
            --add-opens=java.base/java.lang.invoke=ALL-UNNAMED
            --add-opens=java.base/java.lang.reflect=ALL-UNNAMED
            --add-opens=java.base/java.security=ALL-UNNAMED
            --add-opens=java.base/java.util=ALL-UNNAMED
            --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
            --add-opens=java.management/javax.management=ALL-UNNAMED
            --add-opens=java.naming/javax.naming=ALL-UNNAMED
        </modular.jdk.args>
```
https://github.com/wildfly/wildfly/blob/main/pom.xml#L169

It has not come up in JBeret till now. Is it possible to apply this workaround in quarkus-jberet?

**Comment by radcortez** [comment]
Already did and it works as expected. Actually, it only required the security module, but we may have runtime code not being hit requiring additional stuff.

Are we fine with this, or do we want to eventually remove the need of opening these modules?

**Comment by chengfang** [comment]
I think using the above `opens` opts is a sensible workaround. I'll investigate more if removing `WildFlySecurityManager` in jberet would make it easier.

**Comment by maxandersen** [comment]
Any add opens is not a sensible workaround. Its a working workaround but let’s not consider it sensible :)

**Comment by chengfang** [comment]
It will be fixed via https://issues.redhat.com/browse/JBERET-570 and https://issues.redhat.com/browse/JBERET-572

**Comment by chengfang** [comment]
SecurityManager is still used in WildFy, EAP and many user apps, so will be preserved in jberet for now.

**Comment by jamezp** [comment]
+1 the security manager related stuff cannot be removed. In some environments the security manager is mandated. The spec itself even uses it.

**Comment by chengfang** [comment]
FYI, jberet 1.4.8.Final is released on 2022-07-27, which contains the fix for this issue, along with other improvements.
https://github.com/jberet/jsr352/releases/tag/1.4.8.Final
