### ISSUE TITLE
Update the CODEOWNERS file

### ISSUE THREAD

**Issue by liweinan** [jberet/jsr352#361]

**Comment by liweinan** [comment]
Team created: https://github.com/orgs/jberet/teams/reviewers
And set in file: https://github.com/jberet/jsr352/blob/main/CODEOWNERS

**Comment by liweinan** [comment]
@jamezp @chengfang I have set up the team similar to the resteasy settings:

- https://github.com/orgs/resteasy/teams/reviewers
- https://github.com/resteasy/resteasy/blob/main/CODEOWNERS

**Comment by chengfang** [comment]
@jamezp We've been using both jira and github issues for jberet. In general, issues that will not have impact on downstream product, such as project logistics or community-only content, are best to be tracked inside github issues. This allows for easy navigation for community members, and also avoid noises in jira system.
