### ISSUE TITLE
Enable Support to get DB Username/Password from enivonment variable for jberet.properties

### ISSUE THREAD

**Issue by lokeshnaik808** [jberet/jsr352#367]
Currently if JDBC memory type is used, we need to store the DB username passwort etc. as plain text in `jberet.properties` file. There is no way to parse environment variables in BatchSEEnvironment file so that plaintext password need to be given in jberet.properties file to avoid security vulnerability.

**Comment by liweinan** [comment]
@chengfang Do you have any suggestion on this?

**Comment by lokeshnaik808** [comment]
I will create a PR soon for this enhacement

**Comment by liweinan** [comment]
@chengfang I propose a stricter pattern checking to avoid security issues: https://github.com/jberet/jsr352/pull/394 could you pls review it? Thanks! @lokeshnaik808 wdyt about this option?

**Comment by liweinan** [comment]
Add a blog post: https://github.com/jberet/jberet.github.io/pull/8
