### ISSUE TITLE
Method JobListener#afterJob called too early

### ISSUE THREAD

**Issue by Turbokiwi** [jberet/jsr352#48]
Take a look at the class JobExecutionRunner. The method afterJob from registered JobListeners is called before the JobRepository and the status of the Job is updated.

Therefore the Job still has the Status "STARTED" and no EndTime is available at this point. This is somehow confusing.

The StepExecutionRunner behaves differently. The Status of the Step is updated and an EndTime is available at the point, when the method afterStep of registered StepListeners is called

**Comment by chengfang** [comment]
Job listeners are part of the job execution, so if one of the listeners afterJob() fails, the whole job would still fail.  We cannot be sure a job is fully complete and hence don't assign a endTime till all job listeners are done with afterJob().

By looking at [StepExecutionRunner](https://github.com/jberet/jsr352/blob/master/jberet-core/src/main/java/org/jberet/runtime/runner/StepExecutionRunner.java#L153), I see the logic is consistent w/ JobExecutionRunner, though I haven't tested it.

**Comment by chengfang** [comment]
An old spec bug related to this issue:

[Bug 4385 - Spec must specify the effect of throwing Exceptions from Listeners](https://java.net/bugzilla/show_bug.cgi?id=4385)

Excerpt from spec 1.0-rev_A:

8.1.2 Job Level Exception Handling
Any unhandled exception thrown by a job-level listener causes the job to terminate with a batch status of FAILED. In this context, "unhandled" simply means an exception thrown by the listener back to the runtime implementation.

**Comment by chengfang** [comment]
Batch spec discussion on when job execution end time is available (March 2015):
https://java.net/projects/jbatch/lists/public/archive/2015-03/message/0

**Comment by Turbokiwi** [comment]
Saw that also. But it only says, that the endTime is null, as long as the job is not completed, stopped or failed. 
According to Bug 4385 they clarified that an exception inside a listener makes a job having the status failed. The question which status the job has, when JobListener#afterJob() is called an no exception has been thrown is in my opinion not answered by the Spec.

I filed this bug now: https://java.net/bugzilla/show_bug.cgi?id=6975

**Comment by Turbokiwi** [comment]
... but reading again through point 8.7 I come to the following conclusion:
"Status COMPLETED - Batch job has ended normally ....." .... "A job execution will end under the following conditions: 1. A job-level execution element (step, flow, or split) finishes execution, without specifying a "next" attribute and without the exit status matching any transition elements. In this case, the batch status is set to COMPLETED."

And the JavaDoc of JobListener#afterJob() says: "The afterJob method receives control after the job execution ends. "

Doesn't that mean the following?:
1. a Job finishes execution after the last step
2. a finished job is given the status completed
3. JobLister#afterJob() methods are called?

**Comment by chengfang** [comment]
We can optimistically set batch status to COMPLETED after all steps and other job elements complete successfully, before calling job listeners afterJob(), to make it more consistent, even though the final job batch status may be FAILED, if afterJob() throws exception.

Before that is in place, a workaround is to end your job with a <decision> that contains a <end>

```xml
<decision id="decision1" ref="xxx.Decider1">
        <end on="*"/>
</decision>
```

**Comment by Turbokiwi** [comment]
I suggest to wait for a response to the bug I filed on java.net before changing anyting. The decision-element is a neat trick. It also works with an <end /> element directly inside the last step.
