### ISSUE TITLE
Presence of beans.xml in jberet-support

### ISSUE THREAD

**Issue by Turbokiwi** [jberet/jsr352#49]
All necessary Beans are marked with @Dependent and therefore jberet-support is an implicit Bean Archive. Isn't the presence of beans.xml with bean-discovery-mode="annotated" ambiguous.

Because of the presence of the beans.xml jberet-support can't be used in an CDI 1.0 environment (we can't use a higher Version at the moment), when not all optional dependencies are included in the classpath.

To avoid this, jberet-support has to be repackaged without beans.xml in our project.

**Comment by chengfang** [comment]
The original issue for which we added bean-discovery-mode is     

[JBERET-39 Specify bean-discovery-mode in jberet-support beans.xml](https://issues.jboss.org/browse/JBERET-39)

Will need to test how it works if beans.xml is removed.

**Comment by chengfang** [comment]
Looks like beans.xml is required when running in Java SE. If I remove beans.xml from jberet-support, jberet-support unit tests are failing because Weld didnt' create artifacts.

**Comment by Turbokiwi** [comment]
We're running on JBoss EAP 6 (CDI 1.0). Repackaging jberet-support without the beans.xml is not a real pain for us.
If we say, that JSR352 was designed for Java EE 7 and running on an EE 6 server is a rare and special use case, then I would close this issue if you agree.

**Comment by jamezp** [comment]
JSR-352 is only in the Java EE 7 spec. There's a requirement that it compiles to JDK 6 so in theory it could run on Java EE 6 though it's not in the spec.

**Comment by chengfang** [comment]
Repackaging jberet-support is the easiest solution, I think.  jberet-support module belongs more to the application side than the batch container side, so applications are free to repackage it.
