### ISSUE TITLE
Use same Springbatch schema

### ISSUE THREAD

**Issue by ricardojlrufino** [jberet/jsr352#582]
Hi, i have several projects that use spring batch, and a tool to visualize spring batch tables.

I would like to know if it is possible to make jberet use this same schema as if it were a spring project.

**Comment by liweinan** [comment]
@ricardojlrufino Though the Spring Batch and JBeret schema have similar structures, the major difference is that Spring Batch doesn't have to support the Jakarta Batch spec, so they can define the schema structure that better suits their requirements.

For example, the JBeret schema contains a `PARTITION_EXECUTION` table that does not in Spring Batch schema, which must exist to support the Jakarta Batch spec :

<img width="2556" alt="image" src="https://github.com/user-attachments/assets/e8b74db6-3158-4dd8-850a-95142098aa1d">

In addition, JBeret must consider its integration with WildFly/EAP and Quarkus which may need careful change in the table structure.

**Comment by liweinan** [comment]
Close as answered.
