### ISSUE TITLE
After the transaction reaper has run , ChunkRunner  does not clear the transaction from the thread

### ISSUE THREAD

**Issue by krishnarbb** [jberet/jsr352#62]
In https://github.com/jberet/jsr352/blob/master/jberet-core/src/main/java/org/jberet/runtime/runner/ChunkRunner.java  Line 335

 tm.rollback(); is called only for certain status.

However in case when the TransactionReaper has rolled back the transaction, the status will be Status.STATUS_ROLLEDBACK and if tm.rollback  or tm.suspend is never called.

Unless tm.rollback or tm.suspend is called, the thread is still associated with transaction. 
Any new Jobs started will fail if they use this thread already associated with a transaction.

The solution for this would be to add Status.STATUS_ROLLEDBACK and Status.STATUS_NO_TRANSACTION in line 332.

**Comment by krishnarbb** [comment]
A related discussion : https://developer.jboss.org/thread/228534

**Comment by chengfang** [comment]
These transaction status check block was first added in https://github.com/jberet/jsr352/commit/4aa94
 on May 18, 2013

**Comment by chengfang** [comment]
According to the above discussion, it seems calling tm.suspend() is the preferred way.  So change ChunkRunner as follows:
```
 else if (txStatus == Status.STATUS_ROLLEDBACK || txStatus == Status.STATUS_NO_TRANSACTION) {
    //the transaction might have been cancelled by a reaper thread, but has not been disassociated from
    //the current thread, so call tm.suspend() to safely disassociate it.
    tm.suspend();
    stepMetrics.increment(Metric.MetricType.ROLLBACK_COUNT, 1);
}
```
Will that work for you?

**Comment by krishnarbb** [comment]
Yes, That will be the correct fix.

**Comment by chengfang** [comment]
JBeret 1.3.0.Alpha1 released on Dec 14, 2015, which includes this fix.

**Comment by chengfang** [comment]
Just for record, the related commit is:
https://github.com/jberet/jsr352/commit/0336e62554522aa6d4c766a5bda65ec298d8b074

Another related issue in JIRA:
[JBERET-231](https://issues.jboss.org/browse/JBERET-231)
Batch thread tx context not cleaned up properly on tx timeout in chunk-type step
