### ISSUE TITLE
JBERET000601: Failed to get job xml file for job

### ISSUE THREAD

**Issue by mincong-h** [jberet/jsr352#82]
This is a followed issue of #80. I used arquillian to test an installed module containing a batch job. After the succeed deployment of the WAR, I got the below error:

```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 20.696 sec <<< FAILURE! - in org.hibernate.search.jsr352.PerformanceIT
testDiffrentMassIndexer(org.hibernate.search.jsr352.PerformanceIT)  Time elapsed: 7.002 sec  <<< ERROR!
javax.batch.operations.JobStartException: JBERET000601: Failed to get job xml file for job mass-index.xml
	at org.jberet.creation.ArchiveXmlLoader.getJobXml(ArchiveXmlLoader.java:129)
	at org.jberet.creation.ArchiveXmlLoader.loadJobXml(ArchiveXmlLoader.java:91)
	at org.jberet.operations.JobOperatorImpl.start(JobOperatorImpl.java:102)
	at org.hibernate.search.jsr352.MassIndexer.start(MassIndexer.java:90)
	at org.hibernate.search.jsr352.PerformanceIT.testNewMassIndexer(PerformanceIT.java:163)
	at org.hibernate.search.jsr352.PerformanceIT.testDiffrentMassIndexer(PerformanceIT.java:117)
```

My job XML is not found by the batch runtime. Here're some points that I've checked:

- The job XML `mass-index.xml` has been included in the module's jar file. I checked by viewing the Contents of a JAR File. It is located at:

        META-INF/batch-jobs/mass-index.xml

- The SPI of `JobXmlResolver` has been implemented using `org.jberet.tools.MetaInfBatchJobsJobXmlResolver`, it has been included in the module, located at: 

        META-INF/services/org.jberet.spi.JobXmlResolver

- The arquillian deployment works with jboss deploement structure file, where the dependency on the module include a dependency on its META-INF directory, as suggested in the [mailing-list][1].

    ```xml
    <jboss-deployment-structure xmlns="urn:jboss:deployment-structure:1.1">
        <deployment>
            <dependencies>
                <module name="org.hibernate.search.jsr352" services="export" export="true" slot="${project.version}" meta-inf="import"/>
            </dependencies>
        </deployment>
    </jboss-deployment-structure>
    ```

[1]: http://lists.jboss.org/pipermail/wildfly-dev/2016-August/005377.html

**Comment by chengfang** [comment]
I"m a little confused.  Your last paragraph says the arq deployment works with jboss-deployment-structure.xml.  So what is it that is not working?  Can you elaborate under what circumstances you had the errors, and your expected behavior wrt job loading in your module?

**Comment by mincong-h** [comment]
I’m still a student and lack experience in this field, but I’ll try my best to describe the situation.

## Structure of the project

There’re several maven modules in my project and 3 of them are concerned in this issue.

*  `hsearch-jsr352-core` uses JSR 352 to create its batch job, described in `META-INF/batch-jobs/mass-index.xml`
*  `hsearch-jsr352-modules` aims to package the core Maven module `hsearch-jsr352-core` as a module in a container managed WildFly server.
*  `hsearch-jsr352-integrationtest-wildfly` tests the core Maven module installed in WildFly. The test WAR is deployed to the same WF as configured above. The deployment of WAR works with Arquillian and jboss deployment structure.

## Expected behaviors

1. `hsearch-jsr352-modules` packages the core with its meta inf files and install the core into WF as a WF module
2. `hsearch-jsr352-integrationtest-wildfly` deploys the WAR file for integration test
3. Thanks to the jboss-deployment-structure.xml, the test WAR file can detect the core module installed in WF, including the its META-INF folder
4. The `@Test` of the deployed WAR starts
5. The `@Test` asks batch runtime to start the job `mass-index` 
6. JBeret resolves job `mass-index` and find its correspondent XML file from the installed module and then reads the target job `mass-index.xml`. Please notice that the job XML is not located in the WAR, but in the installed module (core). :x:
7. Job starts.

The job failed at step 6.

**Comment by chengfang** [comment]
Thanks for the detailed explanation, now I have better picture what you're trying to do.  Can you step thru in a debugger to see what job loader gets used (your custom job loader, or the default job loader), and their associated class loader, which is used to load job xml as resource.  You can start from, say, org.wildfly.extension.batch.jberet.deployment.JobOperatorService

**Comment by chengfang** [comment]
Are you running the test with Arq embedded?  How did you install your module to the WildFly?  Can you try Arq remote config, or package the test as a standard war and deploy to WildFly, just to eliminate one variable?

**Comment by mincong-h** [comment]
Hi @chengfang, the module is packaged by Maven plugin **maven-assembly-plugin** and installed by Maven plugin **maven-dependency-plugin** with the below script:

```xml
            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>unpack</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>unpack</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>org.wildfly</groupId>
                                    <artifactId>wildfly-dist</artifactId>
                                    <version>${org.wildfly}</version>
                                    <type>zip</type>
                                    <overWrite>true</overWrite>
                                    <outputDirectory>${project.build.directory}/node1</outputDirectory>
                                </artifactItem>
                                <!-- Provide the current project to WildFly as a new module -->
                                <artifactItem>
                                    <groupId>org.hibernate</groupId>
                                    <artifactId>hsearch-jsr352-modules</artifactId>
                                    <version>${project.version}</version>
                                    <classifier>wildfly-10-dist</classifier>
                                    <type>zip</type>
                                    <overWrite>true</overWrite>
                                    <outputDirectory>${project.build.directory}/node1/wildfly-${org.wildfly}/modules</outputDirectory>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

I'm running the test with Arquillian managed. Thanks to @gunnarmorling, I've activated the remote debugger from Eclipse. So I can now debug the managed WF server. However, I can only give a breakpoint to

    javax.batch.operations.JobOperator#start(String, Properties)

But I cannot give a breakpoint to 

    org.jberet.operations.JobOperatorImpl#start(String, Properties)

Any idea how can I achieve the second one?

**Comment by gunnarmorling** [comment]
You need to add the add the right version of JBeret (the Java Batch impl)
as a provided dependency to your project.

**Comment by mincong-h** [comment]
Thx, @gunnarmorling. Yes, you've mentioned in your email, but for some reasons I didn't achieve. Now it works! So @chengfang, the break point is made at the line [102][102] of `JobOperatorImpl` and here're some variables shown in _Variables_ windows from Eclipse.

[102]: https://github.com/jberet/jsr352/blob/7c697c4c8f7461841b35b65a0e4d59e6794e2ba3/jberet-core/src/main/java/org/jberet/operations/JobOperatorImpl.java#L102

-  XmlLoader = `ArchiveXmlLoader`
-  batchEnvironment = `DelegatingBatchEnvironment`
  -  delegate = `BatchEnvironmentServices$WildFlyBatchEnvironment`
    -  jobXmlResolver = `WildFlyJobXmlResolver`
      -  classLoader = `null`

**Comment by chengfang** [comment]
Great progress!  in your test webapp WAR structure, can you add:

WEB-INF/classes/META-INF/batch-jobs

I know yoru job.xml is inside the module, so it's just a dummy dir, or you can even add a dummy-job.xml there.  WildFly might have identified your test webapp as non-batch app.

In your debug output, what's concerning is the null classLoader, and emptySet jobXmlResolvers.

Once you added the dummy job xml files, can you compare the debug output?  If you continue to step into the `loadJobXml` method, you may find more.

**Comment by mincong-h** [comment]
It works by following your suggestion! 💯 😺 I don't know how to add an empty folder to Arquillian, so I added a dummy xml as you said:

    WEB-INF/classes/META-INF/batch-jobs/should-not-be-used.xml

The job `mass-index` started and finished correctly and all the assertions are OK. I also compared the debug output in the method `ArchiveXmlLoader#loadJobXml(String, ClassLoader, List<Job>, JobXmlResolver)` and I found that the variables are exactly the same with or without the batch folder `META-INF/batch-jobs` in the deployment. However, without having the batch jobs folder leads to a failure and having the batch jobs folder makes the test run correctly.

- jobXmlName = "mass-index"
- classLoader = ModuleClassLoader
- jobXmlResolver = WildFlyJobXmlResolver

I think we did a great job for arriving here and I'm really happy about it!! Thanks everybody 👏 👏  Now, the new question is why the batch folder should be added? According the WildFly 10 document [Implicit module dependencies for deployments][1], the _Batch Subsystem_, `javax.batch.api`, should be always added as a dependency without additional trigger. And more importantly, is there any way to avoid adding adding this folder? If Hibernate Search users need to add explicitly this folder `META-INF/batch-jobs` to benefit from the new impl of mass indexing, then we're in a very complicated situation.

[1]: https://docs.jboss.org/author/display/WFLY10/Implicit+module+dependencies+for+deployments

**Comment by jamezp** [comment]
It looks like WildFly was setup to ignore non-batch applications https://github.com/wildfly/wildfly/blob/10.0.0.Final/batch/extension-jberet/src/main/java/org/wildfly/extension/batch/jberet/deployment/WildFlyJobXmlResolver.java#L87-L108. I'd consider this a bug since there is an intention to allow using the `JobXmlResolver` interface.  Would you mind filing an issue here https:// issues.jboss.org/browse/WFLY? If you don't have a user just let me know and I'll file one.

**Comment by jamezp** [comment]
In fact this should fix it https://github.com/wildfly/wildfly/commit/6e869ac64bc50f94a0a6c273d40dcbf261ce0187

**Comment by mincong-h** [comment]
Issue filled: https://issues.jboss.org/browse/WFLY-7000
I didn't mean to assign @chengfang in that issue, but it seems that system did it automatically. BTW, if someone can enhance my description in WFLY-7000, that will be very appreciated.

> In fact this should fix it wildfly/wildfly@6e869ac

How can I download this specific version of WF? Should I add some repo setup in Maven, so that it can download the WF from GitHub instead of Maven center?

**Comment by gunnarmorling** [comment]
> How can I download this specific version of WF?

You can check out and build the WF sources as described here:
https://developer.jboss.org/wiki/HackingOnWildFly

To check out that specific commit, you'd run

    git checkout 6e869ac

Then build it (check how to skip the tests likely to save some time) and
use that snapshot version for your Arquillian test.

Great to see the progress, thanks everyone!

**Comment by mincong-h** [comment]
> In fact this should fix it wildfly/wildfly@6e869ac

I confirmed that the above commit solved this issue. See mincong-h/gsoc-hsearch@0640913 too.

**Comment by jamezp** [comment]
Excellent! Well done @mincong-h. I've got a PR open for it already :) https://github.com/wildfly/wildfly/pull/9154

**Comment by mincong-h** [comment]
Great @jamezp. Thanks everybody!
